const PUZZLES = [
  ["SOUND","DISCO","PIANO","SHARP","late-night set"],
  ["SOUND","DISCO","RADIO","SONAR","on the air"],
  ["SOUND","DISCO","TEMPO","SHOUT","dance floor"],
  ["SOUND","DANCE","GRACE","SWING","ballroom"],
  ["SOUND","DANCE","PRIZE","SHARP","talent night"],
  ["CHOIR","RADIO","DISCO","CROWD","live show"],
  ["CHOIR","RADIO","DISCO","CHORD","harmony"],
  ["CHOIR","ROCKY","MERRY","CHARM","singalong"],
  ["CHOIR","REBEL","METAL","CHARM","loud room"],
  ["MUSIC","CELLO","RADIO","MAJOR","concert hall"],
  ["MUSIC","CELLO","RADIO","MINOR","concert hall"],
  ["MUSIC","CHOIR","CHEER","MAGIC","big number"],
  ["MUSIC","CROWD","CHORD","MAGIC","the show"],
  ["CELLO","OPERA","DRAMA","CROWD","opening night"],
  ["CELLO","OPERA","DRAMA","CHORD","opera house"],
  ["AUDIO","OPERA","DRAMA","AWARD","the arts"],
  ["CROWD","DISCO","RADIO","CHEER","party night"],
  ["CROWD","DISCO","RADIO","CIDER","house party"],
  ["CROWD","DANCE","MOVIE","CHARM","night out"],
  ["CROWD","DANCE","NOISE","CLOWN","carnival"],
  ["SWING","GUEST","TOAST","SHOUT","celebration"],
  ["STAGE","ENJOY","PARTY","SHARP","afterparty"],
  ["CHESS","SCORE","DANCE","CROWD","game night"],
  ["CHESS","SKATE","DANCE","CROWD","rec night"],
  ["CHESS","SPARK","TRACK","COURT","match day"],
  ["LYRIC","CAROL","NOVEL","LEARN","words and songs"],
  ["LEARN","NOVEL","CAROL","LOGIC","study hall"],
  ["CLASS","STAGE","THEME","CHANT","school play"],
  ["CLASS","SCENE","THEME","CHANT","drama class"],
  ["PRINT","THEME","FABLE","PROOF","on the page"],
  ["MEDAL","LIGHT","COURT","MUSIC","awards night"],
  ["WATER","RIVER","LINER","WHIRL","moving water"],
  ["WATER","RAINY","FERRY","WHARF","wet harbor"],
  ["WATER","RAINY","FOGGY","WHARF","gray harbor"],
  ["FJORD","DRIFT","YACHT","FERRY","north water"],
  ["FJORD","DRIFT","TROUT","FLOAT","fishing day"],
  ["COAST","TROUT","DRIFT","CLOUD","shoreline"],
  ["CANAL","LINER","DIVER","CLOUD","inland water"],
  ["CANAL","LINER","RIVER","CLEAR","waterway"],
  ["DELTA","ATOLL","TIDAL","DRIFT","where waters meet"],
  ["DELTA","ATOLL","TOWEL","DRIFT","island day"],
  ["FLOOD","DRIFT","TROUT","FLOAT","after the rain"],
  ["STORM","MOIST","YACHT","SPRAY","rough water"],
  ["STORM","MOIST","YACHT","SALTY","sea weather"],
  ["CLOUD","DIVER","RIVER","CLEAR","over the water"],
  ["CLOUD","DIVER","LINER","CORAL","sea and sky"],
  ["FLOAT","TROUT","YACHT","FERRY","boats and fish"],
  ["FLOAT","TIDAL","TOWEL","FLEET","beach day"],
  ["FERRY","YACHT","TROUT","FLEET","on the water"],
  ["WHARF","FLOAT","YACHT","WINDY","docks"],
  ["WHARF","FLEET","YACHT","WINDY","harbor wind"],
  ["CORAL","LINER","RIVER","CLEAR","water routes"],
  ["FOGGY","YACHT","TROUT","FLOAT","misty catch"],
  ["STEAM","MOIST","YACHT","SUNNY","warm water day"],
  ["STEAM","MOIST","YACHT","SPRAY","hot harbor"],
  ["BREAD","DONUT","YEAST","BERRY","bakery case"],
  ["CRUST","TOAST","YEAST","CANDY","sweet oven"],
  ["FLOUR","ROAST","TOAST","FEAST","baked table"],
  ["SUGAR","ROAST","TOAST","SWEET","dessert tray"],
  ["SUGAR","ROAST","YEAST","SALTY","kitchen counter"],
  ["SWEET","TOAST","YEAST","SALTY","snack table"],
  ["GLASS","SWEET","TOAST","GUEST","dinner party"],
  ["PORCH","HOUSE","LODGE","PANEL","home place"],
  ["PORCH","HOUSE","TABLE","PLANT","front room"],
  ["PORCH","HOUSE","HEDGE","PEACH","yard and house"],
  ["PORCH","HEDGE","THYME","PLANT","kitchen garden"],
  ["PORCH","HOUSE","LODGE","PETAL","garden house"],
  ["SHELF","FRAME","TABLE","SHEET","inside the house"],
  ["SHELF","FRAME","LEDGE","STILL","quiet rooms"],
  ["SHELF","FRESH","PORCH","SLEEP","quiet house"],
  ["PANEL","LODGE","TABLE","PLANT","cabin room"],
  ["PANEL","LIGHT","TOAST","PLANT","sunny kitchen"],
  ["LIGHT","TOAST","NIGHT","LEMON","evening kitchen"],
  ["BLIND","DRAIN","LEMON","BASIL","kitchen window"],
  ["MOTEL","LODGE","HOUSE","MULCH","places to stay"],
  ["GLASS","SHADE","STOVE","GRASS","house and yard"],
  ["GLASS","SHADE","STONE","GRASS","patio"],
  ["GLASS","SHADE","SMOKE","GRASS","backyard fire"],
  ["CABIN","NIGHT","ROAST","CHAIR","cabin evening"],
  ["ATTIC","COUCH","MULCH","ALARM","old house"],
  ["BURST","TOAST","LIGHT","BROIL","hot oven"],
  ["CLEAR","ROAST","NIGHT","CABIN","cookout cabin"],
  ["GROVE","EAGLE","SHADE","GRASS","tree line"],
  ["GROVE","EAGLE","STONE","GRASS","parkland"],
  ["CEDAR","RIDGE","LODGE","CHILL","mountain stay"],
  ["CEDAR","RANGE","LODGE","CHILL","high country"],
  ["BIRCH","HEDGE","MAPLE","BLOOM","planted yard"],
  ["MAPLE","EAGLE","HEDGE","MULCH","yard work"],
  ["SHRUB","BIRCH","EARTH","SHADE","under the trees"],
  ["FENCE","EAGLE","HEDGE","FINCH","backyard"],
  ["CLIFF","FENCE","LODGE","CHILL","edge of the woods"],
  ["RIDGE","EAGLE","RANGE","RIVER","high country"],
  ["WRIST","TOOTH","THIGH","WAIST","the body"],
  ["GUILT","TEARY","MERRY","GLEAM","mixed feelings"],
  ["GUILT","TEARY","MERCY","GLEAM","heavy heart"],
  ["GUILT","TOOTH","MOUTH","GLEAM","face and feeling"],
  ["CRUSH","HAPPY","MERRY","CHARM","soft heart"],
  ["CROSS","SWEAT","HEART","CRUSH","worked up"],
  ["SLEEP","PEACE","TENSE","STOUT","restless night"],
  ["CHILL","LIVER","SOBER","CROSS","under the weather"],
  ["CROWN","NOBLE","TITLE","COURT","the crown"],
  ["COURT","THEFT","HEIST","CATCH","the case"],
  ["PEARL","LEGAL","ROYAL","POWER","high society"],
  ["HONOR","ROYAL","TRIAL","HEART","duty"],
  ["HEIST","TITLE","TRACE","HEART","the plot"],
  ["FLARE","EARTH","HARSH","FLASH","harsh light"],
  ["FLASH","HARSH","EARTH","FLAME","heat lightning"],
  ["CHARM","MERCY","HONEY","CATCH","sweetness"],
  ["GRACE","EAGER","FEVER","GRIEF","rising feeling"],
];
